spring.application.name=smart-url-shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/Smart-url-shortner
spring.datasource.username=postgres
spring.datasource.password=rahul123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true